controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController 

        gripper_position_controller:
            type: position_controllers/JointGroupPositionController            

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        effort_controller:
            type: effort_controllers/JointGroupEffortController


position_controller:
    ros__parameters:
        joints:
            - link_1_joint 
            - link_2_joint
            - link_3_joint
            - link_4_joint
            - link_5_joint
            - link_6_joint
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity
            - effort

gripper_position_controller:
    ros__parameters:
        joints:
            - left_finger_1_joint
            - right_finger_1_joint
            - left_finger_2_joint
            - right_finger_2_joint
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity
            - effort


effort_controller:
    ros__parameters:
        joints:
            - link_1_joint 
            - link_2_joint
            - link_3_joint
            - link_4_joint
            - link_5_joint
            - link_6_joint
            - left_finger_1_joint
            - right_finger_1_joint
            - left_finger_2_joint
            - right_finger_2_joint

        interface_name: effort
        command_interfaces:
            - effort
        state_interfaces:
            - position
            - velocity
            - effort